openapi: 3.1.0
info:
  title: Flow-Ledger Currency API
  version: 1.0.0
  description: >
    货币与历史汇率、批量换算接口。来源：Flow-Ledger 需求。
servers:
  - url: https://api.example.com/v1
security:
  - OAuth2: [read:currency]
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:currency: 读取货币与汇率
        clientCredentials:
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:currency: 读取货币与汇率
  headers:
    XRequestId:
      description: 请求ID
      schema: { type: string }
    XRateLimitLimit:
      description: 限流总额
      schema: { type: integer }
    XRateLimitRemaining:
      description: 剩余额度
      schema: { type: integer }
    XRateLimitReset:
      description: 重置时间戳（秒）
      schema: { type: integer }
    IdempotencyKey:
      description: 幂等键回显
      schema: { type: string }
  parameters:
    Page:
      in: query
      name: page
      schema: { type: integer, minimum: 1, default: 1 }
    PageSize:
      in: query
      name: page_size
      schema: { type: integer, minimum: 1, maximum: 200, default: 20 }
    From:
      in: query
      name: from
      description: 起始时间（UTC）
      schema: { type: string, format: date-time }
    To:
      in: query
      name: to
      description: 截止时间（UTC）
      schema: { type: string, format: date-time }
    FilterCode:
      in: query
      name: filter[code]
      schema: { type: string, pattern: '^[A-Z]{3}$' }
  schemas:
    Money:
      type: object
      properties:
        amount: { type: string, pattern: '^-?\d+(\.\d{1,6})?$' }
        currency: { type: string, pattern: '^[A-Z]{3}$' }
      required: [amount, currency]
    Currency:
      type: object
      properties:
        code: { type: string, pattern: '^[A-Z]{3}$' }
        name: { type: string }
        symbol: { type: string }
        scale: { type: integer, minimum: 0, maximum: 6 }
      required: [code, name, scale]
    ExchangeRate:
      type: object
      properties:
        base: { type: string, pattern: '^[A-Z]{3}$' }
        quote: { type: string, pattern: '^[A-Z]{3}$' }
        date: { type: string, format: date }
        rate: { type: string, pattern: '^\d+(\.\d{1,10})?$' }
      required: [base, quote, date, rate]
    Error:
      type: object
      properties:
        code: { type: string }
        message: { type: string }
        details: {}
  responses:
    Unauthorized:
      description: 未授权
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
paths:
  /currencies:
    get:
      tags: [currency]
      summary: 货币列表
      security: [{ OAuth2: [read:currency] }]
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/FilterCode'
      responses:
        '200':
          description: 成功
          headers:
            X-Request-Id: { $ref: '#/components/headers/XRequestId' }
            X-RateLimit-Limit: { $ref: '#/components/headers/XRateLimitLimit' }
            X-RateLimit-Remaining: { $ref: '#/components/headers/XRateLimitRemaining' }
            X-RateLimit-Reset: { $ref: '#/components/headers/XRateLimitReset' }
          content:
            application/json:
              schema:
                type: object
                properties:
                  total: { type: integer }
                  page: { type: integer }
                  page_size: { type: integer }
                  has_next: { type: boolean }
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Currency' }
        '401': { $ref: '#/components/responses/Unauthorized' }
  /currencies/{code}:
    get:
      tags: [currency]
      summary: 货币详情
      parameters:
        - in: path
          name: code
          required: true
          schema: { type: string, pattern: '^[A-Z]{3}$' }
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Currency' }
        '404':
          description: 未找到
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
  /exchange-rates:
    get:
      tags: [exchange-rate]
      summary: 历史汇率查询
      parameters:
        - in: query
          name: base
          required: true
          schema: { type: string, pattern: '^[A-Z]{3}$' }
        - in: query
          name: quote
          required: true
          schema: { type: string, pattern: '^[A-Z]{3}$' }
        - in: query
          name: date
          required: false
          schema: { type: string, format: date }
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/ExchangeRate' }
  /convert:
    post:
      tags: [convert]
      summary: 批量金额换算
      parameters:
        - in: header
          name: Idempotency-Key
          required: false
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                at:
                  type: string
                  format: date-time
                  description: 换算时间（UTC）
                items:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    properties:
                      amount: { type: string, pattern: '^-?\d+(\.\d{1,6})?$' }
                      from: { type: string, pattern: '^[A-Z]{3}$' }
                      to: { type: string, pattern: '^[A-Z]{3}$' }
                    required: [amount, from, to]
              required: [items]
      responses:
        '200':
          description: 成功
          headers:
            X-Request-Id: { $ref: '#/components/headers/XRequestId' }
            Idempotency-Key: { $ref: '#/components/headers/IdempotencyKey' }
          content:
            application/json:
              schema:
                type: object
                properties:
                  at: { type: string, format: date-time }
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        from: { $ref: '#/components/schemas/Money' }
                        to: { $ref: '#/components/schemas/Money' }
        '422':
          description: 校验失败
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
