openapi: 3.1.0
info:
  title: Flow-Ledger Currency API
  version: 1.0.0
  description: Currency and FX endpoints for Flow-Ledger.
servers:
  - url: https://api.example.com/v1
security:
  - OAuth2: [read:currency]
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:currency: Read currency and FX data
        clientCredentials:
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:currency: Read currency and FX data
  headers:
    XRequestId:
      description: Request ID
      schema: { type: string }
    XRateLimitLimit:
      description: Rate limit total
      schema: { type: integer }
    XRateLimitRemaining:
      description: Remaining quota
      schema: { type: integer }
    XRateLimitReset:
      description: Reset time (seconds)
      schema: { type: integer }
    IdempotencyKey:
      description: Idempotency key
      schema: { type: string }
  parameters:
    Page:
      in: query
      name: page
      schema: { type: integer, minimum: 1, default: 1 }
    PageSize:
      in: query
      name: page_size
      schema: { type: integer, minimum: 1, maximum: 200, default: 20 }
    Code:
      in: query
      name: code
      schema: { type: string, pattern: '^[A-Z]{3}$' }
    Query:
      in: query
      name: q
      description: Search by currency name or symbol
      schema: { type: string }
    Sort:
      in: query
      name: sort
      description: Comma separated fields, prefix with "-" for descending
      schema: { type: string, default: code }
  schemas:
    Currency:
      type: object
      properties:
        code: { type: string, pattern: '^[A-Z]{3}$' }
        name: { type: string }
        symbol: { type: string, nullable: true }
        scale: { type: integer, minimum: 0, maximum: 6 }
      required: [code, name, scale]
    CurrencyPage:
      type: object
      properties:
        total: { type: integer }
        page: { type: integer }
        page_size: { type: integer }
        has_next: { type: boolean }
        items:
          type: array
          items: { $ref: '#/components/schemas/Currency' }
      required: [total, page, page_size, has_next, items]
    CurrencyUpsert:
      type: object
      properties:
        code: { type: string, pattern: '^[A-Z]{3}$' }
        name: { type: string }
        symbol: { type: string, nullable: true }
        scale: { type: integer, minimum: 0, maximum: 6 }
      required: [code, name, scale]
    CurrencyPatch:
      type: object
      properties:
        name: { type: string, nullable: true }
        symbol: { type: string, nullable: true }
        scale: { type: integer, minimum: 0, maximum: 6, nullable: true }
    ExchangeRateSingle:
      type: object
      properties:
        base: { type: string, pattern: '^[A-Z]{3}$' }
        quote: { type: string, pattern: '^[A-Z]{3}$' }
        date: { type: string, format: date }
        rate: { type: string }
        effective_date: { type: string, format: date }
      required: [base, quote, date, rate, effective_date]
    ExchangeRateMap:
      type: object
      additionalProperties:
        type: object
        properties:
          rate: { type: string }
          effective_date: { type: string, format: date }
        required: [rate, effective_date]
    ExchangeRateRangeItem:
      type: object
      properties:
        date: { type: string, format: date }
        rate: { type: string }
      required: [date, rate]
    ExchangeRateRange:
      type: object
      properties:
        base: { type: string, pattern: '^[A-Z]{3}$' }
        quote: { type: string, pattern: '^[A-Z]{3}$' }
        from_date: { type: string, format: date }
        to_date: { type: string, format: date }
        items:
          type: array
          items: { $ref: '#/components/schemas/ExchangeRateRangeItem' }
      required: [base, quote, from_date, to_date, items]
    ConvertRequest:
      type: object
      properties:
        amount: { type: string, pattern: '^-?\\d+(\\.\\d{1,6})?$' }
        from: { type: string, pattern: '^[A-Z]{3}$' }
        to: { type: string, pattern: '^[A-Z]{3}$' }
        date: { type: string, format: date }
      required: [amount, from, to]
    ConvertResponse:
      type: object
      properties:
        amount: { type: string }
        from_currency: { type: string, pattern: '^[A-Z]{3}$' }
        to_currency: { type: string, pattern: '^[A-Z]{3}$' }
        rate: { type: string }
        converted: { type: string }
        effective_date: { type: string, format: date }
      required: [amount, from_currency, to_currency, rate, converted, effective_date]
    ImportExchangeRateUpload:
      type: object
      properties:
        file: { type: string, format: binary }
      required: [file]
    ImportTaskCreateResponse:
      type: object
      properties:
        task_id: { type: string }
      required: [task_id]
    ImportTaskStatus:
      type: object
      properties:
        task_id: { type: string }
        kind: { type: string }
        status: { type: string, enum: [queued, processing, succeeded, failed] }
        progress: { type: integer, minimum: 0, maximum: 100 }
        stage: { type: string, nullable: true }
        filename: { type: string, nullable: true }
        size: { type: integer, nullable: true }
        result: { type: object, nullable: true }
        error: { type: string, nullable: true }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
      required: [task_id, kind, status, progress, created_at, updated_at]
    BulkUpsertResult:
      type: object
      properties:
        code: { type: string, pattern: '^[A-Z]{3}$' }
        status: { type: string, enum: [created, updated] }
      required: [code, status]
    Error:
      type: object
      properties:
        detail: { type: string }
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
paths:
  /currencies:
    get:
      tags: [currency]
      summary: List currencies
      security: [{ OAuth2: [read:currency] }]
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/Code'
        - $ref: '#/components/parameters/Query'
        - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: Success
          headers:
            X-Request-Id: { $ref: '#/components/headers/XRequestId' }
            X-RateLimit-Limit: { $ref: '#/components/headers/XRateLimitLimit' }
            X-RateLimit-Remaining: { $ref: '#/components/headers/XRateLimitRemaining' }
            X-RateLimit-Reset: { $ref: '#/components/headers/XRateLimitReset' }
          content:
            application/json:
              schema: { $ref: '#/components/schemas/CurrencyPage' }
        '401': { $ref: '#/components/responses/Unauthorized' }
    post:
      tags: [currency]
      summary: Create or replace a currency
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CurrencyUpsert' }
      responses:
        '200':
          description: Upserted
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Currency' }
  /currencies/{code}:
    get:
      tags: [currency]
      summary: Get currency by code
      parameters:
        - in: path
          name: code
          required: true
          schema: { type: string, pattern: '^[A-Z]{3}$' }
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Currency' }
        '404':
          description: Not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
    patch:
      tags: [currency]
      summary: Patch currency fields
      parameters:
        - in: path
          name: code
          required: true
          schema: { type: string, pattern: '^[A-Z]{3}$' }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CurrencyPatch' }
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Currency' }
        '404':
          description: Not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        '422':
          description: Invalid scale
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
  /currencies/bulk:
    put:
      tags: [currency]
      summary: Bulk upsert currencies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items: { $ref: '#/components/schemas/CurrencyUpsert' }
      responses:
        '200':
          description: Result per item
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items: { $ref: '#/components/schemas/BulkUpsertResult' }
                required: [results]
  /exchange-rates:
    get:
      tags: [exchange-rate]
      summary: Get exchange rates
      parameters:
        - in: query
          name: base
          required: true
          schema: { type: string, pattern: '^[A-Z]{3}$' }
        - in: query
          name: quote
          required: false
          schema: { type: string, pattern: '^[A-Z]{3}$' }
        - in: query
          name: date
          required: false
          schema: { type: string, format: date }
      responses:
        '200':
          description: Success
          content:
            application/json:
              oneOf:
                - $ref: '#/components/schemas/ExchangeRateSingle'
                - type: object
                  properties:
                    base: { type: string, pattern: '^[A-Z]{3}$' }
                    date: { type: string, format: date }
                    rates: { $ref: '#/components/schemas/ExchangeRateMap' }
                  required: [base, date, rates]
        '404':
          description: Rate not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
  /exchange-rates/sync:
    post:
      tags: [exchange-rate]
      summary: Sync asset FX rates to target currency
      parameters:
        - in: query
          name: target
          required: false
          schema: { type: string, pattern: '^[A-Z]{3}$', default: CNY }
      responses:
        '200':
          description: Sync triggered
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '500':
          description: Sync error
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
  /exchange-rates/range:
    get:
      tags: [exchange-rate]
      summary: Get exchange rates within a date range
      parameters:
        - in: query
          name: base
          required: true
          schema: { type: string, pattern: '^[A-Z]{3}$' }
        - in: query
          name: quote
          required: true
          schema: { type: string, pattern: '^[A-Z]{3}$' }
        - in: query
          name: from
          required: true
          schema: { type: string, format: date }
        - in: query
          name: to
          required: true
          schema: { type: string, format: date }
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ExchangeRateRange' }
        '404':
          description: Rate not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
  /import/exchange-rates:
    post:
      tags: [exchange-rate]
      summary: 批量导入汇率
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema: { $ref: '#/components/schemas/ImportExchangeRateUpload' }
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ImportTaskCreateResponse' }
  /import/exchange-rates/tasks/{task_id}:
    get:
      tags: [exchange-rate]
      summary: 查询导入任务进度
      parameters:
        - in: path
          name: task_id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ImportTaskStatus' }
  /convert:
    post:
      tags: [convert]
      summary: Convert amount between currencies
      parameters:
        - in: header
          name: Idempotency-Key
          required: false
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ConvertRequest' }
      responses:
        '200':
          description: Success
          headers:
            X-Request-Id: { $ref: '#/components/headers/XRequestId' }
            Idempotency-Key: { $ref: '#/components/headers/IdempotencyKey' }
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ConvertResponse' }
        '404':
          description: Rate not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        '422':
          description: Validation failed
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
