openapi: 3.1.0
info:
  title: Flow-Ledger Custom API
  version: 1.0.0
  description: 自定义统计与聚合接口
servers:
  - url: https://api.example.com/v1
security:
  - OAuth2: [read:deposit]
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:deposit: 读取存款/资产资源
  schemas:
    InstitutionAssetChange:
      type: object
      properties:
        institution_id: { type: integer, format: int64 }
        institution_name: { type: string }
        institution_type: { type: string, enum: [bank, broker, other] }
        current_as_of: { type: string, format: date-time }
        previous_as_of: { type: string, format: date-time }
        current_total: { type: string, pattern: '^\d+(\.\d{1,6})?$' }
        previous_total: { type: string, pattern: '^\d+(\.\d{1,6})?$' }
        delta: { type: string, pattern: '^-?\d+(\.\d{1,6})?$' }
      required:
        [
          institution_id,
          institution_name,
          institution_type,
          current_as_of,
          previous_as_of,
          current_total,
          previous_total,
          delta,
        ]
    InstitutionAssetChangeList:
      type: object
      properties:
        currency: { type: string, pattern: '^[A-Z]{3}$' }
        total: { type: integer }
        data:
          type: array
          items: { $ref: '#/components/schemas/InstitutionAssetChange' }
      required: [currency, total, data]
    MonthlyAssetPoint:
      type: object
      properties:
        month: { type: string, format: date }
        amount: { type: string, pattern: '^\d+(\.\d{1,6})?$' }
      required: [month, amount]
    MonthlyAssetTrend:
      type: object
      properties:
        currency: { type: string, pattern: '^[A-Z]{3}$' }
        data:
          type: array
          items: { $ref: '#/components/schemas/MonthlyAssetPoint' }
      required: [currency, data]
    ExpensePeriodCompare:
      type: object
      properties:
        currency: { type: string, pattern: '^[A-Z]{3}$' }
        current_from: { type: string, format: date-time }
        current_to: { type: string, format: date-time }
        current_total: { type: string, pattern: '^-?\d+(\.\d{1,6})?$' }
        previous_from: { type: string, format: date-time }
        previous_to: { type: string, format: date-time }
        previous_total: { type: string, pattern: '^-?\d+(\.\d{1,6})?$' }
        delta: { type: string, pattern: '^-?\d+(\.\d{1,6})?$' }
        delta_rate: { type: string, pattern: '^-?\d+(\.\d{1,6})?$' }
      required:
        [
          currency,
          current_from,
          current_to,
          current_total,
          previous_from,
          previous_to,
          previous_total,
          delta,
          delta_rate,
        ]
paths:
  /custom/expenses/total/compare:
    get:
      tags: [custom]
      summary: 指定时长内消费支出总额与上一周期对比（按用户基准货币）
      parameters:
        - in: query
          name: from
          required: true
          schema: { type: string, format: date-time }
        - in: query
          name: to
          required: true
          schema: { type: string, format: date-time }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ExpensePeriodCompare' }
  /custom/assets/monthly:
    get:
      tags: [custom]
      summary: 每月总资产变化（按用户基准货币）
      parameters:
        - in: query
          name: from
          schema: { type: string, format: date-time }
        - in: query
          name: to
          schema: { type: string, format: date-time }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 200 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/MonthlyAssetTrend' }
  /custom/institutions/assets/changes:
    get:
      tags: [custom]
      summary: 机构资产变动排行（与上次记录对比）
      parameters:
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 200, default: 10 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/InstitutionAssetChangeList' }
