openapi: 3.1.0
info:
  title: Flow-Ledger Deposit API
  version: 1.1.0
  description: 用户金融机构、金融产品与余额快照管理接口
servers:
  - url: https://api.example.com/v1
security:
  - OAuth2: [read:deposit, write:deposit]
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:deposit: 读取存款/资产资源
            write:deposit: 写入存款/资产资源
  headers:
    IdempotencyKey: { schema: { type: string } }
  parameters:
    Page: { in: query, name: page, schema: { type: integer, minimum: 1, default: 1 } }
    PageSize: { in: query, name: page_size, schema: { type: integer, minimum: 1, maximum: 200, default: 20 } }
  schemas:
    Institution:
      type: object
      properties:
        id: { type: integer, format: int64 }
        name: { type: string }
        type: { type: string, enum: [bank, broker, other] }
        product_number: { type: integer }
      required: [id, name, type, product_number]
    InstitutionList:
      type: object
      properties:
        total: { type: integer }
        page: { type: integer }
        page_size: { type: integer }
        has_next: { type: boolean }
        data:
          type: array
          items: { $ref: '#/components/schemas/Institution' }
    InstitutionCreate:
      type: object
      properties:
        name: { type: string, minLength: 1, maxLength: 128 }
        type: { type: string, enum: [bank, broker, other] }
      required: [name, type]
    InstitutionPatch:
      type: object
      properties:
        name: { type: string, minLength: 1, maxLength: 128 }
        type: { type: string, enum: [bank, broker, other] }
    Product:
      type: object
      properties:
        id: { type: integer, format: int64 }
        institution_id: { type: integer, format: int64 }
        name: { type: string }
        product_type: { type: string, enum: [deposit, investment, securities, other] }
        currency: { type: string, pattern: '^[A-Z]{3}$' }
        status: { type: string, enum: [active, inactive, closed] }
        risk_level: { type: string, enum: [flexible, stable, high_risk] }
        amount: { type: string, pattern: '^\d+(\.\d{1,6})?$' }
        amount_updated_at: { type: string, format: date-time }
        institution_name: { type: string }
        institution_type: { type: string, enum: [bank, broker, other] }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
      required: [id, institution_id, name, product_type, currency, status, risk_level, amount, amount_updated_at, institution_name, institution_type]
    ProductList:
      type: object
      properties:
        total: { type: integer }
        page: { type: integer }
        page_size: { type: integer }
        has_next: { type: boolean }
        data:
          type: array
          items: { $ref: '#/components/schemas/Product' }
    ProductCreate:
      type: object
      properties:
        institution_id: { type: integer, format: int64 }
        name: { type: string, minLength: 1, maxLength: 128 }
        product_type: { type: string, enum: [deposit, investment, securities, other], default: deposit }
        currency: { type: string, pattern: '^[A-Z]{3}$' }
        status: { type: string, enum: [active, inactive, closed], default: active }
        risk_level: { type: string, enum: [flexible, stable, high_risk], default: stable }
        amount: { type: string, pattern: '^\d+(\.\d{1,6})?$', nullable: true }
      required: [institution_id, name, currency]
    ProductPatch:
      type: object
      properties:
        name: { type: string, minLength: 1, maxLength: 128 }
        product_type: { type: string, enum: [deposit, investment, securities, other] }
        status: { type: string, enum: [active, inactive, closed] }
        risk_level: { type: string, enum: [flexible, stable, high_risk] }
    Balance:
      type: object
      properties:
        id: { type: integer, format: int64 }
        product_id: { type: integer, format: int64 }
        amount: { type: string, pattern: '^\d+(\.\d{1,6})?$' }
        as_of: { type: string, format: date-time }
      required: [id, product_id, amount, as_of]
    BalanceCreate:
      type: object
      properties:
        amount: { type: string, pattern: '^\d+(\.\d{1,6})?$', minimum: 0 }
        as_of: { type: string, format: date-time }
      required: [amount, as_of]
    BalanceList:
      type: object
      properties:
        total: { type: integer }
        page: { type: integer }
        page_size: { type: integer }
        has_next: { type: boolean }
        data:
          type: array
          items: { $ref: '#/components/schemas/Balance' }
paths:
  /institutions:
    get:
      tags: [deposit]
      summary: 机构列表
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - in: query
          name: type
          schema: { type: string, enum: [bank, broker, other] }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/InstitutionList' }
    post:
      tags: [deposit]
      summary: 创建机构
      parameters:
        - in: header
          name: Idempotency-Key
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/InstitutionCreate' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Institution' }
  /institutions/{id}:
    patch:
      tags: [deposit]
      summary: 更新机构
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, format: int64 }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/InstitutionPatch' }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Institution' }
  /products:
    get:
      tags: [deposit]
      summary: 金融产品列表
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - in: query
          name: institution_id
          schema: { type: integer, format: int64 }
        - in: query
          name: product_type
          schema: { type: string, enum: [deposit, investment, securities, other] }
        - in: query
          name: status
          schema: { type: string, enum: [active, inactive, closed] }
        - in: query
          name: risk_level
          schema: { type: string, enum: [flexible, stable, high_risk] }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ProductList' }
    post:
      tags: [deposit]
      summary: 创建金融产品
      parameters:
        - in: header
          name: Idempotency-Key
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ProductCreate' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Product' }
  /products/{id}:
    patch:
      tags: [deposit]
      summary: 更新金融产品
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, format: int64 }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ProductPatch' }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Product' }
  /products/{id}/balances:
    get:
      tags: [deposit]
      summary: 产品余额历史
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, format: int64 }
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - in: query
          name: from
          schema: { type: string, format: date-time }
        - in: query
          name: to
          schema: { type: string, format: date-time }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/BalanceList' }
    post:
      tags: [deposit]
      summary: 写入余额快照
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/BalanceCreate' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Balance' }
