openapi: 3.1.0
info:
  title: Flow-Ledger Expense API
  version: 1.0.0
  description: 消费记录与分类接口。来源：Flow-Ledger 需求。
servers:
  - url: https://api.example.com/v1
security:
  - OAuth2: [read:expense, write:expense]
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:expense: 读取消费
            write:expense: 写消费
        clientCredentials:
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:expense: 读取消费
            write:expense: 写消费
  headers:
    XRequestId: { schema: { type: string } }
    IdempotencyKey: { schema: { type: string } }
  parameters:
    Page: { in: query, name: page, schema: { type: integer, minimum: 1, default: 1 } }
    PageSize: { in: query, name: page_size, schema: { type: integer, minimum: 1, maximum: 200, default: 20 } }
    From: { in: query, name: from, schema: { type: string, format: date-time } }
    To: { in: query, name: to, schema: { type: string, format: date-time } }
  schemas:
    Expense:
      type: object
      properties:
        id: { type: integer, format: int64, readOnly: true }
        amount: { type: string, pattern: '^\d+(\.\d{1,6})?$' }
        currency: { type: string, pattern: '^[A-Z]{3}$' }
        category_id: { type: integer, format: int64, nullable: true }
        merchant: { type: string, nullable: true }
        paid_account_id: { type: integer, format: int64, nullable: true }
        occurred_at: { type: string, format: date-time }
        source_ref: { type: string, nullable: true }
        note: { type: string, nullable: true }
      required: [amount, currency, occurred_at]
    Category:
      type: object
      properties:
        id: { type: integer, format: int64, readOnly: true }
        name: { type: string }
      required: [name]
    Error:
      type: object
      properties: { code: {type: string}, message: {type: string}, details: {} }
paths:
  /expenses:
    post:
      tags: [expense]
      summary: 创建消费
      parameters:
        - in: header
          name: Idempotency-Key
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Expense' }
      responses:
        '201':
          description: 已创建
          headers:
            X-Request-Id: { $ref: '#/components/headers/XRequestId' }
            Idempotency-Key: { $ref: '#/components/headers/IdempotencyKey' }
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Expense' }
        '409':
          description: 幂等冲突
          content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } }
    get:
      tags: [expense]
      summary: 查询消费
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/From'
        - $ref: '#/components/parameters/To'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  total: { type: integer }
                  page: { type: integer }
                  page_size: { type: integer }
                  has_next: { type: boolean }
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Expense' }
  /categories:
    get:
      tags: [expense]
      summary: 分类列表
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Category' }
    post:
      tags: [expense]
      summary: 新建分类
      parameters:
        - in: header
          name: Idempotency-Key
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Category' }
      responses:
        '201':
          description: 已创建
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Category' }
