openapi: 3.1.0
info:
  title: Flow-Ledger Expense API
  version: 1.0.0
  description: 消费记录与分类接口。来源：Flow-Ledger 需求。
servers:
  - url: https://api.example.com/v1
security:
  - OAuth2: [read:expense, write:expense]
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:expense: 读取消费
            write:expense: 写消费
        clientCredentials:
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read:expense: 读取消费
            write:expense: 写消费
  headers:
    XRequestId: { schema: { type: string } }
    IdempotencyKey: { schema: { type: string } }
  parameters:
    Page: { in: query, name: page, schema: { type: integer, minimum: 1, default: 1 } }
    PageSize: { in: query, name: page_size, schema: { type: integer, minimum: 1, maximum: 200, default: 20 } }
    From: { in: query, name: from, schema: { type: string, format: date-time } }
    To: { in: query, name: to, schema: { type: string, format: date-time } }
  schemas:
    Expense:
      type: object
      properties:
        id: { type: integer, format: int64, readOnly: true }
        amount: { type: string, pattern: '^\d+(\.\d{1,6})?$' }
        currency: { type: string, pattern: '^[A-Z]{3}$' }
        category_id: { type: integer, format: int64, nullable: true }
        merchant: { type: string, nullable: true }
        paid_account_id: { type: integer, format: int64, nullable: true }
        occurred_at: { type: string, format: date-time }
        source_ref: { type: string, nullable: true }
        note: { type: string, nullable: true }
      required: [amount, currency, occurred_at]
    ExpensePatch:
      type: object
      properties:
        amount: { type: string, pattern: '^\d+(\.\d{1,6})?$' }
        currency: { type: string, pattern: '^[A-Z]{3}$' }
        category_id: { type: integer, format: int64, nullable: true }
        merchant: { type: string, nullable: true }
        paid_account_id: { type: integer, format: int64, nullable: true }
        occurred_at: { type: string, format: date-time }
        source_ref: { type: string, nullable: true }
        note: { type: string, nullable: true }
    ExpenseBatchIn:
      type: object
      properties:
        items:
          type: array
          items: { $ref: '#/components/schemas/Expense' }
    ExpenseBatchItem:
      type: object
      properties:
        index: { type: integer }
        status: { type: string }
        expense: { $ref: '#/components/schemas/Expense' }
        error: { type: string, nullable: true }
    ExpenseBatchOut:
      type: object
      properties:
        total: { type: integer }
        created: { type: integer }
        failed: { type: integer }
        items:
          type: array
          items: { $ref: '#/components/schemas/ExpenseBatchItem' }
    ReceiptOcrResult:
      type: object
      properties:
        消费名称: { type: string }
        消费金额: { type: number }
        消费商家名称: { type: string }
        消费时间: { type: string }
        消费分类: { type: string }
    Category:
      type: object
      properties:
        id: { type: integer, format: int64, readOnly: true }
        name: { type: string }
      required: [name]
    Error:
      type: object
      properties: { code: {type: string}, message: {type: string}, details: {} }
paths:
  /expenses:
    post:
      tags: [expense]
      summary: 创建消费
      parameters:
        - in: header
          name: Idempotency-Key
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Expense' }
      responses:
        '201':
          description: 已创建
          headers:
            X-Request-Id: { $ref: '#/components/headers/XRequestId' }
            Idempotency-Key: { $ref: '#/components/headers/IdempotencyKey' }
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Expense' }
        '409':
          description: 幂等冲突
          content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } }
    get:
      tags: [expense]
      summary: 查询消费
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/From'
        - $ref: '#/components/parameters/To'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  total: { type: integer }
                  page: { type: integer }
                  page_size: { type: integer }
                  has_next: { type: boolean }
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Expense' }
  /expenses/batch:
    post:
      tags: [expense]
      summary: Batch create expenses
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ExpenseBatchIn' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ExpenseBatchOut' }
  /expenses/{expense_id}:
    get:
      tags: [expense]
      summary: Get expense by id
      parameters:
        - in: path
          name: expense_id
          required: true
          schema: { type: integer, format: int64 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Expense' }
        '404':
          description: Not found
          content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } }
    patch:
      tags: [expense]
      summary: Update expense
      parameters:
        - in: path
          name: expense_id
          required: true
          schema: { type: integer, format: int64 }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ExpensePatch' }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Expense' }
        '404':
          description: Not found
          content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } }
    delete:
      tags: [expense]
      summary: Delete expense
      parameters:
        - in: path
          name: expense_id
          required: true
          schema: { type: integer, format: int64 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Expense' }
        '404':
          description: Not found
          content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } }
  /import/expense/receipt:
    post:
      tags: [expense]
      summary: Upload receipt image for OCR
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id: { type: string }
  /import/expense/receipt/tasks/{task_id}:
    get:
      tags: [expense]
      summary: Get receipt OCR task result
      parameters:
        - in: path
          name: task_id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id: { type: string }
                  kind: { type: string }
                  status: { type: string }
                  progress: { type: integer }
                  stage: { type: string, nullable: true }
                  filename: { type: string, nullable: true }
                  size: { type: integer, nullable: true }
                  result: { $ref: '#/components/schemas/ReceiptOcrResult' }
                  error: { type: string, nullable: true }
                  created_at: { type: string, format: date-time }
                  updated_at: { type: string, format: date-time }
  /categories:
    get:
      tags: [expense]
      summary: 分类列表
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Category' }
    post:
      tags: [expense]
      summary: 新建分类
      parameters:
        - in: header
          name: Idempotency-Key
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/Category' }
      responses:
        '201':
          description: 已创建
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Category' }
