-- Flow-Ledger Currency schema (PostgreSQL 12+)
-- Creates schema, tables, constraints, triggers, indexes, and seed data

CREATE SCHEMA IF NOT EXISTS currency;

-- Per-schema updated_at trigger
CREATE OR REPLACE FUNCTION currency.tg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

CREATE TABLE IF NOT EXISTS currency.currencies (
  code        TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  symbol      TEXT NULL,
  scale       INT  NOT NULL DEFAULT 2,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_currencies__scale CHECK (scale BETWEEN 0 AND 6)
);

CREATE TRIGGER trg_currencies__upd
BEFORE UPDATE ON currency.currencies
FOR EACH ROW EXECUTE FUNCTION currency.tg_set_updated_at();

CREATE TABLE IF NOT EXISTS currency.exchange_rates (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_code   TEXT NOT NULL REFERENCES currency.currencies(code) ON DELETE RESTRICT,
  quote_code  TEXT NOT NULL REFERENCES currency.currencies(code) ON DELETE RESTRICT,
  rate_date   DATE NOT NULL,
  rate        NUMERIC(20,10) NOT NULL,
  source      TEXT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_exchange_rates__pair_date UNIQUE (base_code, quote_code, rate_date),
  CONSTRAINT ck_exchange_rates__positive CHECK (rate > 0),
  CONSTRAINT ck_exchange_rates__not_same CHECK (base_code <> quote_code)
);

CREATE TRIGGER trg_exchange_rates__upd
BEFORE UPDATE ON currency.exchange_rates
FOR EACH ROW EXECUTE FUNCTION currency.tg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_exchange_rates__pair_date_desc
ON currency.exchange_rates (base_code, quote_code, rate_date DESC);

-- Seeds
INSERT INTO currency.currencies(code, name, symbol, scale)
VALUES ('USD','US Dollar','$',2)
ON CONFLICT (code) DO NOTHING;

INSERT INTO currency.currencies(code, name, symbol, scale)
VALUES ('CNY','Chinese Yuan','¥',2)
ON CONFLICT (code) DO NOTHING;

INSERT INTO currency.currencies(code, name, symbol, scale)
VALUES ('HKD','Hong Kong Dollar','HK$',2)
ON CONFLICT (code) DO NOTHING;

INSERT INTO currency.currencies(code, name, symbol, scale)
VALUES ('JPY', 'Japanese Yen','¥',0)
ON CONFLICT (code) DO NOTHING;

