-- Flow-Ledger Deposit schema (PostgreSQL 12+)

CREATE SCHEMA IF NOT EXISTS deposit;

CREATE OR REPLACE FUNCTION deposit.tg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

CREATE TABLE IF NOT EXISTS deposit.institutions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  type       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_institutions__type CHECK (type IN ('bank','broker','other'))
);

DROP TRIGGER IF EXISTS trg_institutions__upd ON deposit.institutions;
CREATE TRIGGER trg_institutions__upd
BEFORE UPDATE ON deposit.institutions
FOR EACH ROW EXECUTE FUNCTION deposit.tg_set_updated_at();

CREATE TABLE IF NOT EXISTS deposit.accounts (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL REFERENCES "user".users(id) ON DELETE RESTRICT,
  institution_id  BIGINT NOT NULL REFERENCES deposit.institutions(id) ON DELETE RESTRICT,
  currency        TEXT   NOT NULL REFERENCES currency.currencies(code) ON DELETE RESTRICT,
  status          TEXT   NOT NULL DEFAULT 'active',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_accounts__status CHECK (status IN ('active','inactive'))
);

CREATE INDEX IF NOT EXISTS idx_accounts__user_id ON deposit.accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_accounts__institution_id ON deposit.accounts(institution_id);

DROP TRIGGER IF EXISTS trg_accounts__upd ON deposit.accounts;
CREATE TRIGGER trg_accounts__upd
BEFORE UPDATE ON deposit.accounts
FOR EACH ROW EXECUTE FUNCTION deposit.tg_set_updated_at();

CREATE TABLE IF NOT EXISTS deposit.account_balances (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES deposit.accounts(id) ON DELETE CASCADE,
  amount     NUMERIC(20,6) NOT NULL,
  as_of      TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_account_balances__account_asof UNIQUE (account_id, as_of),
  CONSTRAINT ck_account_balances__amount_nonneg CHECK (amount >= 0)
);

-- Optional monthly partition example (create as needed)
-- CREATE TABLE deposit.account_balances_2025_01 PARTITION OF deposit.account_balances
-- FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');

CREATE INDEX IF NOT EXISTS idx_account_balances__as_of_desc
ON deposit.account_balances (as_of DESC);

DROP TRIGGER IF EXISTS trg_account_balances__upd ON deposit.account_balances;
CREATE TRIGGER trg_account_balances__upd
BEFORE UPDATE ON deposit.account_balances
FOR EACH ROW EXECUTE FUNCTION deposit.tg_set_updated_at();

-- Seeds
INSERT INTO deposit.institutions(name, type) VALUES ('Example Bank','bank')
ON CONFLICT (name) DO NOTHING;

INSERT INTO deposit.accounts(user_id, institution_id, currency)
SELECT 1, i.id, 'USD' FROM deposit.institutions i WHERE i.name='Example Bank'
ON CONFLICT DO NOTHING;

INSERT INTO deposit.account_balances(account_id, amount, as_of)
SELECT a.id, 1000.00, now() FROM deposit.accounts a
LIMIT 1;
