-- Flow-Ledger Expense schema (PostgreSQL 12+)

CREATE SCHEMA IF NOT EXISTS expense;

CREATE OR REPLACE FUNCTION expense.tg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

CREATE TABLE IF NOT EXISTS expense.expense_categories (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES "user".users(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  parent_id  BIGINT NULL REFERENCES expense.expense_categories(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_expense_categories__user_name UNIQUE (user_id, name)
);

CREATE TRIGGER trg_expense_categories__upd
BEFORE UPDATE ON expense.expense_categories
FOR EACH ROW EXECUTE FUNCTION expense.tg_set_updated_at();

CREATE TABLE IF NOT EXISTS expense.expenses (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL REFERENCES "user".users(id) ON DELETE RESTRICT,
  amount          NUMERIC(20,6) NOT NULL,
  currency        TEXT   NOT NULL REFERENCES currency.currencies(code) ON DELETE RESTRICT,
  category_id     BIGINT NULL REFERENCES expense.expense_categories(id) ON DELETE SET NULL,
  merchant        TEXT   NULL,
  tags            TEXT[] NULL,
  paid_account_id BIGINT NULL REFERENCES deposit.accounts(id) ON DELETE SET NULL,
  occurred_at     TIMESTAMPTZ NOT NULL,
  source_ref      TEXT   NULL,
  note            TEXT   NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_expenses__amount_positive CHECK (amount >= 0)
);

CREATE TRIGGER trg_expenses__upd
BEFORE UPDATE ON expense.expenses
FOR EACH ROW EXECUTE FUNCTION expense.tg_set_updated_at();

-- Idempotency for external imports when source_ref is provided
CREATE UNIQUE INDEX IF NOT EXISTS idx_expenses__user_source_ref
ON expense.expenses (user_id, source_ref)
WHERE source_ref IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_expenses__user_occurred_at_desc
ON expense.expenses (user_id, occurred_at DESC);

-- Seeds
INSERT INTO expense.expense_categories(user_id, name) VALUES (1,'订阅')
ON CONFLICT DO NOTHING;

INSERT INTO expense.expenses(user_id, amount, currency, category_id, merchant, occurred_at, note)
SELECT 1, 11.990000, 'USD', c.id, 'YouTube', now(), '会员订阅'
FROM expense.expense_categories c WHERE c.user_id=1 AND c.name='订阅'
LIMIT 1;

