-- Flow-Ledger File schema (PostgreSQL 12+)

CREATE SCHEMA IF NOT EXISTS file;

CREATE OR REPLACE FUNCTION file.tg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

CREATE TABLE IF NOT EXISTS file.files (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES "user".users(id) ON DELETE CASCADE,
  filename     TEXT NOT NULL,
  content_type TEXT NULL,
  storage_path TEXT NOT NULL,
  size         BIGINT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_files__user_id
ON file.files (user_id);

DROP TRIGGER IF EXISTS trg_files__upd ON file.files;
CREATE TRIGGER trg_files__upd
BEFORE UPDATE ON file.files
FOR EACH ROW EXECUTE FUNCTION file.tg_set_updated_at();
