-- Flow-Ledger Loan schema (PostgreSQL 12+)

CREATE SCHEMA IF NOT EXISTS loan;

CREATE OR REPLACE FUNCTION loan.tg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

CREATE TABLE IF NOT EXISTS loan.counterparties (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  type       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_counterparties__type CHECK (type IN ('institution','person')),
  CONSTRAINT uq_counterparties__name UNIQUE (name)
);

DROP TRIGGER IF EXISTS trg_counterparties__upd ON loan.counterparties;
CREATE TRIGGER trg_counterparties__upd
BEFORE UPDATE ON loan.counterparties
FOR EACH ROW EXECUTE FUNCTION loan.tg_set_updated_at();

CREATE TABLE IF NOT EXISTS loan.loans (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL REFERENCES "user".users(id) ON DELETE RESTRICT,
  counterparty_id BIGINT NOT NULL REFERENCES loan.counterparties(id) ON DELETE RESTRICT,
  principal       NUMERIC(20,6) NOT NULL,
  currency        TEXT   NOT NULL REFERENCES currency.currencies(code) ON DELETE RESTRICT,
  rate_type       TEXT   NOT NULL,
  rate_value      NUMERIC(20,10) NOT NULL,
  term_months     INT    NOT NULL,
  start_date      TIMESTAMPTZ NOT NULL,
  status          TEXT   NOT NULL DEFAULT 'active',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_loans__principal_nonneg CHECK (principal >= 0),
  CONSTRAINT ck_loans__rate_nonneg CHECK (rate_value >= 0),
  CONSTRAINT ck_loans__term_pos CHECK (term_months > 0),
  CONSTRAINT ck_loans__rate_type CHECK (rate_type IN ('fixed','floating')),
  CONSTRAINT ck_loans__status CHECK (status IN ('active','closed','defaulted'))
);

CREATE INDEX IF NOT EXISTS idx_loans__user_id ON loan.loans(user_id);

DROP TRIGGER IF EXISTS trg_loans__upd ON loan.loans;
CREATE TRIGGER trg_loans__upd
BEFORE UPDATE ON loan.loans
FOR EACH ROW EXECUTE FUNCTION loan.tg_set_updated_at();

CREATE TABLE IF NOT EXISTS loan.loan_schedules (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id        BIGINT NOT NULL REFERENCES loan.loans(id) ON DELETE CASCADE,
  period_no      INT    NOT NULL,
  due_date       TIMESTAMPTZ NOT NULL,
  principal_due  NUMERIC(20,6) NOT NULL,
  interest_due   NUMERIC(20,6) NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_loan_schedules__loan_period UNIQUE (loan_id, period_no),
  CONSTRAINT ck_loan_schedules__principal_nonneg CHECK (principal_due >= 0),
  CONSTRAINT ck_loan_schedules__interest_nonneg CHECK (interest_due >= 0)
);

CREATE INDEX IF NOT EXISTS idx_loan_schedules__due_date
ON loan.loan_schedules (due_date);

DROP TRIGGER IF EXISTS trg_loan_schedules__upd ON loan.loan_schedules;
CREATE TRIGGER trg_loan_schedules__upd
BEFORE UPDATE ON loan.loan_schedules
FOR EACH ROW EXECUTE FUNCTION loan.tg_set_updated_at();

CREATE TABLE IF NOT EXISTS loan.loan_txns (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id        BIGINT NOT NULL REFERENCES loan.loans(id) ON DELETE RESTRICT,
  period_no      INT NULL,
  paid_at        TIMESTAMPTZ NOT NULL,
  principal_paid NUMERIC(20,6) NOT NULL DEFAULT 0,
  interest_paid  NUMERIC(20,6) NOT NULL DEFAULT 0,
  fee_paid       NUMERIC(20,6) NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Optional partition example
-- CREATE TABLE loan.loan_txns_2025_01 PARTITION OF loan.loan_txns
-- FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');

CREATE INDEX IF NOT EXISTS idx_loan_txns__loan_paid_at
ON loan.loan_txns (loan_id, paid_at DESC);

DROP TRIGGER IF EXISTS trg_loan_txns__upd ON loan.loan_txns;
CREATE TRIGGER trg_loan_txns__upd
BEFORE UPDATE ON loan.loan_txns
FOR EACH ROW EXECUTE FUNCTION loan.tg_set_updated_at();

-- Seeds
INSERT INTO loan.counterparties(name, type) VALUES ('Example Lender','institution')
ON CONFLICT DO NOTHING;

INSERT INTO loan.loans(user_id, counterparty_id, principal, currency, rate_type, rate_value, term_months, start_date)
SELECT 1, c.id, 10000.00, 'USD', 'fixed', 0.0500000000, 12, now()
FROM loan.counterparties c WHERE c.name='Example Lender'
ON CONFLICT DO NOTHING;

INSERT INTO loan.loan_schedules(loan_id, period_no, due_date, principal_due, interest_due)
SELECT l.id, 1, now() + interval '30 days', 800.00, 50.00
FROM loan.loans l LIMIT 1;
