-- Flow-Ledger User schema (PostgreSQL 12+)

CREATE SCHEMA IF NOT EXISTS "user";

CREATE OR REPLACE FUNCTION "user".tg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

CREATE TABLE IF NOT EXISTS "user".users (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_user_id BIGINT NULL UNIQUE,
  is_bot_enabled   BOOLEAN NOT NULL DEFAULT true,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_users__upd
BEFORE UPDATE ON "user".users
FOR EACH ROW EXECUTE FUNCTION "user".tg_set_updated_at();

CREATE TABLE IF NOT EXISTS "user".user_prefs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT NOT NULL UNIQUE REFERENCES "user".users(id) ON DELETE CASCADE,
  base_currency TEXT   NOT NULL REFERENCES currency.currencies(code) ON DELETE RESTRICT,
  timezone      TEXT   NOT NULL,
  language      TEXT   NOT NULL DEFAULT 'zh-CN',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_user_prefs__tz CHECK (length(timezone) BETWEEN 1 AND 64)
);

CREATE TRIGGER trg_user_prefs__upd
BEFORE UPDATE ON "user".user_prefs
FOR EACH ROW EXECUTE FUNCTION "user".tg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_users__telegram_user_id
ON "user".users (telegram_user_id);

-- Seeds
INSERT INTO "user".users(telegram_user_id) VALUES (NULL) ON CONFLICT DO NOTHING;

INSERT INTO "user".user_prefs(user_id, base_currency, timezone, language)
SELECT u.id, 'USD', 'UTC', 'zh-CN'
FROM "user".users u
WHERE NOT EXISTS (
  SELECT 1 FROM "user".user_prefs p WHERE p.user_id = u.id
)
LIMIT 1;

