-- Flow-Ledger User schema (PostgreSQL 12+)

CREATE SCHEMA IF NOT EXISTS "user";

CREATE OR REPLACE FUNCTION "user".tg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

CREATE TABLE IF NOT EXISTS "user".users (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username         TEXT   NULL UNIQUE,
  email            TEXT   NULL UNIQUE,
  password_hash    TEXT   NULL,
  password_salt    TEXT   NULL,
  last_login_at    TIMESTAMPTZ NULL,
  telegram_user_id BIGINT NULL UNIQUE,
  is_bot_enabled   BOOLEAN NOT NULL DEFAULT true,
  email_verification_token TEXT NULL,
  email_verification_expires_at TIMESTAMPTZ NULL,
  email_verified_at TIMESTAMPTZ NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_users__upd ON "user".users;
CREATE TRIGGER trg_users__upd
BEFORE UPDATE ON "user".users
FOR EACH ROW EXECUTE FUNCTION "user".tg_set_updated_at();

CREATE TABLE IF NOT EXISTS "user".user_prefs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT NOT NULL UNIQUE REFERENCES "user".users(id) ON DELETE CASCADE,
  base_currency TEXT   NOT NULL REFERENCES currency.currencies(code) ON DELETE RESTRICT,
  timezone      TEXT   NOT NULL,
  language      TEXT   NOT NULL DEFAULT 'zh-CN',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_user_prefs__tz CHECK (length(timezone) BETWEEN 1 AND 64)
);

DROP TRIGGER IF EXISTS trg_user_prefs__upd ON "user".user_prefs;
CREATE TRIGGER trg_user_prefs__upd
BEFORE UPDATE ON "user".user_prefs
FOR EACH ROW EXECUTE FUNCTION "user".tg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_users__telegram_user_id
ON "user".users (telegram_user_id);
