-- Migration helper: auth/email columns (idempotent).
ALTER TABLE "user".users
    DROP COLUMN IF EXISTS email_verification_token;
ALTER TABLE "user".users
    DROP COLUMN IF EXISTS email_verification_expires_at;
ALTER TABLE "user".users
    DROP COLUMN IF EXISTS password_reset_token;
ALTER TABLE "user".users
    DROP COLUMN IF EXISTS password_reset_expires_at;
CREATE TABLE IF NOT EXISTS "user".auth_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user".users(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    token_type TEXT NOT NULL,
    expires_at TIMESTAMPTZ NULL,
    is_valid BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_auth_tokens__type CHECK (token_type IN ('email_verification','password_reset'))
);
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_class WHERE relname = 'trg_auth_tokens__upd'
    ) THEN
        CREATE TRIGGER trg_auth_tokens__upd
        BEFORE UPDATE ON "user".auth_tokens
        FOR EACH ROW EXECUTE FUNCTION "user".tg_set_updated_at();
    END IF;
END;
$$;
CREATE INDEX IF NOT EXISTS idx_auth_tokens__user_type
ON "user".auth_tokens (user_id, token_type);
-- Ensure unique constraints for username/email.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'up_fin_products__inst_product'
    ) THEN
        ALTER TABLE "deposit".financial_products ADD CONSTRAINT up_fin_products__inst_product UNIQUE (institution_id, name);
    END IF;
END;
$$;
